# Generated by Django 6.0.3 on 2026-04-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_approve_posts', 'Can approve posts')]},
        ),
    ]
